### ISSUE TITLE
Add repository dynamically

### ISSUE THREAD

**Issue by dmitry-php** [composer/satis#112]
Hi
Can you implement adding repository to satis dynamically? I mean when someone request package that not exists in satis it will add this package automatically.
Thanks

**Comment by samsamm777** [comment]
+1

**Comment by alcohol** [comment]
This is virtually impossible since there is no way Satis can determine what the source should be for the missing package.

**Comment by debugteam** [comment]
> This is virtually impossible since there is no way Satis can determine what the source should be for the missing package.

Reading this and beeing confronted with the same problem, i actually see a solution:

I would recommend integrating a command into composer like this:

php composer.phar configure-proxy

It should read the composer.json, search for composer repositories (other than packagist.org) and send the composer.json via REST API.

An input-argument like "api" could be used to set a specific server upload location. e.g.:

php composer.phar configure-proxy api=http://path-to-satis.tld/upload/

Since there is allready some code to be used to analyze the composer.json here:

https://code.tutsplus.com/tutorials/setting-up-a-local-mirror-for-composer-packages-with-satis--net-36726

...i think i could make that happen.

Any ideas or comments?

@Seldaek  @jadb @niksamokhvalov @naderman @johnstevenson @alcohol

**Comment by alcohol** [comment]
If you can come up with an implementation that does not involve modifying composer, I would be open to hearing more about it. But anything that involves modifying composer has a no vote from my perspective. Satis should operate independently of composer, and composer should know nothing about how Satis operates. Composer sees it as nothing more than a provider of metadata, just like Packagist.

**Comment by debugteam** [comment]
Of course one could just run a script to update the cache like:

composer run-script pre-package-install

The defined script could as well upload the composer.json

**Comment by planktonfun** [comment]
Is there a way to cache dump-autoloading result, it makes sense to cache it when no commit updates occured from the composer.lock file. 
basically:
1st step:  composer update // write lock file, generate autoload file
2nd step: composer update // read lock file, if no folders|vendors changes and autoload exist, do not generate autoload file
