### ISSUE TITLE
(Different) error messages when running build multiple times

### ISSUE THREAD

**Issue by bretrzaun** [composer/satis#128]
When running the build command multiple times, we get different results with each execution.

Sometime it runs through without any errors and lists all tags and branches.
Sometimes tags are missing.
In other cases there is this error message:
```
Skipped parsing master, DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character
                                                                                                                                                       
  [Composer\Repository\InvalidRepositoryException]                                                                                                     
  No valid composer.json was found in any branch or tag of ssh://coderepository/..git, could not load a package from it.  
```
Of course there is a composer.json in all branches.

**Comment by TomaszSzymczak** [comment]
In case someone has similar problem:

I had this issue on OSX while building satis via "php bin/satis build <configuration file> <build dir>" command. I was using MAMP and saw date.timezone set in php.ini.

I've just forgotter that php command opens osx's php instead of mamp's for which I've created a bash alias "phpmamp" some time ago :) So now Satis doesn't skip master and composer.json is OK as it has always been.
