### ISSUE TITLE
Prioritize Repository?

### ISSUE THREAD

**Issue by tobi-pb** [composer/satis#226]
Thanks for your great job maintaining this tool.

I'm looking for a solution to prioritize a repository when a package (with same name) exists in repo A and in repo B. Both repos are not under my control.

Actually it just loads data from packagist:

```
{
   "require" : {
    "magento/product-community-edition" : ">=0.74.0-beta12"
   },
   "require-dependencies": true,
   "archive": {
        "directory": "dist",
        "skip-dev": true
    },
   "name": "Magento2 Clone",
   "description": "informaton.",
   "repositories": [
      { "type": "composer", "url": "https://packages.magento.com" },
      { "type": "composer", "url": "http://packagist.org/" }
   ]
}
```

It would like to archive package from magento.com, not from packagist.org 

What is "the composer"-way doing this? 

Thanks a lot,

Tobi

**Comment by stof** [comment]
This is not something for Satis. It is something for Composer. And currently, this is not possible. The order of repositories determines the priority

**Comment by stof** [comment]
btw, in your case, I think you just need to change the order of repositories in the config file

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.

**Comment by rthideaway** [comment]
I need exactly this, I need to give packagist lower priority, because package I am trying to install is outdated  in packagist. In source github repository there is updated version, but I am simply not able to use it since the packagist has bigger priority. I could fork repo, change the package name and use in composer.json, but that's surely overkill. Is there a way to somehow prioritize custom repository package over packagist? Since this is closed I suppose there's not :/

**Comment by alcohol** [comment]
By default, any repository defined in your composer.json has priority over packagist.org. Since packagist.org is disabled by default for satis, to enable it you need to add it as a repository. Order matters here. However, which repository gets picked also depends on the constraint given.

**Comment by rthideaway** [comment]
How obvious! Thanks for explaining, that worked out, at least it seems so!
