### ISSUE TITLE
Class 'Composer\Command\Command' not found in BuildCommand

### ISSUE THREAD

**Issue by 7ochem** [composer/satis#337]
I was using `"composer/satis": "~1.0"` in the composer.json of my Satis setup and retrieved Satis version **1.0.0-alpha1**

When trying to build, I got this error:

> PHP Fatal error:  Class 'Composer\Command\Command' not found in vendor/composer/satis/src/Composer/Satis/Command/BuildCommand.php on line 45

Build command:

    php vendor/bin/satis build satis.json web

**Comment by stof** [comment]
Satis 1.0.0-alpha1 was using a pre-1.0 version of Composer, and is not compatible with the stable version.
When installing Satis on its own, things are working fine because 1.0.0-alpha1 has a lock file asking for a specific composer version. but when using Satis as a dependency, deps are resolved based your project, and so it will take a newer composer version.
If you want to keep using Satis this way, I suggest you to use the dev version of Satis.
