### ISSUE TITLE
Not showing tagged release versions

### ISSUE THREAD

**Issue by zonemann** [composer/satis#379]
Hello there!

We are running Satis in combination with our own gitlab. 

satis.json:
```
{
  "name": "*** Repository",
  "homepage": "http://packages.our.code:1337",
  "repositories": [
    {
      "type": "vcs",
      "url": "https://codestuff.git"
    },
        {
      "type": "vcs",
      "url": "https://othercodestuff.git"
    }

  ],
  "require-all": true
}
```

In gitlab, we have for both repos master & dev branch, as well as tagged versions such as "v0.5.0". Kicking off satis its just fetching dev-master and dev-develop... Tagged versions are neither shown in the web view nor by running composer. Master & develop work flawlessly. Any ideas why the tagged versions aren't fetched?

**Comment by alcohol** [comment]
Can you share the composer json of the package in question, from one of the tags?

**Comment by zonemann** [comment]
You mean the package where the tag release should be fetched? Sure, here:

```
{
    "name": "***/****",
    "version": "0.5.0",
    "type": "library",
    "authors": [
        {
....
    ],
    "require": {
        "twig/twig": "^1.24",
        "filp/whoops": "^2.1",
        "vlucas/phpdotenv": "^2.4",
        "symfony/http-foundation": "^3.1",
        "symfony/routing": "^3.1"
    },
    "options": {
        "secure-http": false
    },
    "autoload": {
        "classmap": [
            "src/Facades"
        ],
        "files": [
            "src/Foundation/Helpers.php"
        ],
        "psr-4": {
            "App\\": "src/"
        }
    }
}
```

**Comment by stof** [comment]
Does the ``version`` field matches the version from the tag name ? If no, this is your issue (as composer will consider it as an invalid release).

the composer doc strongly recommends to omit the ``version`` when using a VCS repo, because it brings exactly no value, but can mark a release as invalid if you forget to update it, so it has only drawbacks in this case.

**Comment by zonemann** [comment]
@stof Yes, the version name does equal the tag name, i tried both with "0.5.0" and "v0.5.0" as version & tag names... Okay, i left out the version number on a new tag, still it's not shown as Release at the Satis Packages.

**Comment by alcohol** [comment]
Did you tag new versions, or did you update them? And when you updated them, did you make sure your composer cache was empty?

**Comment by zonemann** [comment]
@alcohol I tried both, and i also tried with a cleaned composer cache, yes...

**Comment by zonemann** [comment]
@alcohol Ah wait, actually it seems i didnt push as new version.. I used git flow for another try and now it worked... So it seems like updating is not working- Even by cleaning the composer's cache?

**Comment by alcohol** [comment]
I could only speculate, but I would rather not. In the future, be sure to use git tags exclusively, and avoid hardcoding version attribute + value in composer.json :-)

**Comment by zonemann** [comment]
@alcohol Okay, thanks! :)

**Comment by stof** [comment]
Git is based on the assumption that tags are immutable. Replacing a git tag is hard, because all people fetching the repo have to delete the tag locally and fetch it again, otherwise they never see the updated git tag (this is not related to composer, but to the way git works).
So the rule about replacing git tags is simple: don't do it. Create a new tag with a different name instead (for instance ``0.5.0.1``)
