### ISSUE TITLE
Authenication asked when not set

### ISSUE THREAD

**Issue by timurgafarov** [composer/satis#406]
I created a new repo with Satis. However when I am trying to require it from another project for testing, it is asking for authentication. I didn't set any username or passwords. Is there any way to disable authentication?

**Comment by alcohol** [comment]
Problem not clear, cannot help.

**Comment by andrewhowdencom** [comment]
@timurgafarov The HTTP webserver (apache or NGINX) will ask for auth if you have configured it to. You could test this by just executing

```
curl https://path.to.your.website/
```

Composer just uses basic auth, I think. (At least, that works with the satis server I admin)

**Comment by timurgafarov** [comment]
Thank you for your response.

I was actually able to resolve my problem and it turned out that this website is not accessible via web. My Satis web directory had broken permissions. However it was very misleading, in this cases I would expect composer to throw an error saying that url is not accessible or something along those lines.

At this point it looks like composer gives authentication prompts every-time url is not valid or does not have a repo in it. It probably relates more to composer issue rather Satis I would admit.

**Comment by timurgafarov** [comment]
andrewhowdencom,

You actually answered my other question. I am planning to implement an authentication in future and didn't know that it should be done via .htaccess file. Good to know, thanks.

**Comment by andrewhowdencom** [comment]
Disclaimer: I know little about the Satis or composer codebases, this is a derivation from first principles.

> I was actually able to resolve my problem and it turned out that this website is not accessible via web. My Satis web directory had broken permissions. However it was very misleading, in this cases I would expect composer to throw an error saying that url is not accessible or something along those lines.

That kind of makes sense, Apache/NGINX will probably serve a 401/403 if it cannot read the dir. 

A quick look at the composer codebase does indeed seem to indicate that it just listens for the HTTP 401 (unauthorised) status code to determine whether to prompt for credentials:

https://github.com/composer/composer/blob/00a6b7c794d863c4a9b5d5000731b4ec31369ec5/src/Composer/Util/RemoteFilesystem.php#L532

With a further quick look, it looks like it would be possible to determine whether HTTP auth is prompted with additional header, rather than just checking the status code:

https://tools.ietf.org/html/rfc7235#section-4.1

However, I'm not sure that this is 100 percent reliable, and changing the prompt would be a reasonably large change in behaviour. Such a thing seems likely to break somewhere.

I think on balance it's a reasonable solution to simply try basic auth when presented with a 401. However, I might suggest adding a PR to the docs that explains this problem, as well as the things to check (permissions on local DIR, HTTP headers as well as making a request through cURL)

Otherwise, perhaps this issue can be closed? <3

**Comment by timurgafarov** [comment]
andrewhowdencom,

Thanks for a thorough response, that makes sense. I not familiar enough with how authentication is implemented on Apache side to offer a solution. I agree that, this is something that would be good to have in documentation.

Closing the issue.
