### ISSUE TITLE
Slow satis repo update

### ISSUE THREAD

**Issue by ingtarius** [composer/satis#476]
Hello! We have a satis server instance in local network for mirroring external repos (around 200) and it take a loooong time to update (15 min or above).
How to optimize this time? 
Any clue or link with Best Practices?

**Comment by SvenRtbg** [comment]
For comparison: I have close to 600 packages (both internal and external) in my satis instance, and the Jenkins job finishes in around 5 minutes when barely any new packages have been added.

This brings me to the obvious question: What are you doing? Bring more details. Maybe your internet connection is slow, or Github is slow, or your CPU, or the machine is swapping because it is out of memory.

**Comment by ingtarius** [comment]
Here is my satis.json in short version
`{
	"name":"Example",
	"homepage":"http://packages.example.com",
	"config": {
		"process-timeout": 6000
	},
	"repositories": [
		{ "type": "vcs", "url": "ssh://git@repo:7999/bla-bla.git" },
                .... (248 other vcs)
		{ "type": "composer", "url": "http://packagist.org" }
	],
	"require": {
		"core/image": ">=0.0.1",
		.... (330 other packages )
		"darkaonline/l5-swagger":"5.6.*"
	},
	"require-dependencies": true,
	"minimum-stability": "stable",
	"archive": {
		"directory": "dist",
		"format": "tar",
		"skip-dev": true
	}
}`

I cant find bottleneck: ram, cpu and network is fine.
Any caching options in satis?

**Comment by SvenRtbg** [comment]
I'm using a 2-step-process: First grab external dependencies from packagist and create an intermediate satis repo (without archiving anything, just grab meta data), then grab all internal repos including the intermediate satis repo (with only meta data). This requires two config files (because you cannot combine the different tasks) and two directories for the results.

**Comment by ingtarius** [comment]
Can you post example of your configs?

**Comment by SvenRtbg** [comment]
I can!

The external dependencies are first fetched without any distribution ZIP in mind.
```
{
    "name": "External Packages",
    "homepage": "https://example.com/satis/external",
    "repositories": [
        {
            "type":"composer",
            "url":"https://packagist.org"
        }
    ],
    "require": {
        "psr/http-message": ">=1.0",
        "psr/log": ">=1.0",
    },
    "output-html": false,
    "require-dependencies": true
}
```

This creates a Satis repo that is included in the second step, together with all internal software repos. ZIPs are created from everything.
```
{
    "name": "Satis Repository",
    "homepage": "https://example.com/satis/all",
    "repositories": [
        {
            "type": "composer",
            "url": "https://example.com/satis/external"
        },
        {
            "type": "git",
            "url": "ssh://git@example.com/path/software.git"
        }
    ],
    "require-all": true,
    "archive": {
        "directory": "dist",
        "format": "zip",
        "prefix-url": "https://example.com/satis/all",
        "skip-dev": true
    }
}
```

The update process has some more steps, e.g. I query the Git repo server for a list of all known repos and add them dynamically to the second configuration file so that it does not need to be updated by a human if new repos appear, and I do post-process the abandoned flag like this: https://gist.github.com/SvenRtbg/2cf56388ac996870f380

**Comment by SvenRtbg** [comment]
There is more potential for optimization, though, that I currently do not use: Satis is able to selectively update only certain packages. This reduces the amount of operations needed when dumping the ZIP files because at that point Satis knows which repos contain the package requested, and will only scan and dump from these. However, it will still need to scan all repos beforehand in order to know where the requested package is located.

Test runs reduces my 5-6 minutes run time down to about 1 to 2 minutes. Satis simply spends less time detecting that a dump already exists. However, it wasn't such a significant speedup to be implemented right away, so I don't have any real-world experience.

**Comment by staabm** [comment]
@ingtarius we did some Performance work and things should be fast with newer versions.

Is it fast enough for you now? If not, could you provide some profiles, e.g. with blackfire or similar?

**Comment by ingtarius** [comment]
We will try new version.
Thanks for your support!
