### ISSUE TITLE
UI: toggle visibility of fields per entry

### ISSUE THREAD

**Issue by alcohol** [composer/satis#513]
It would be nice if the following fields could be enabled/disabled on the fly, e.g. show or hide the "author" attribute of all packages.

- [ ] homepage
- [ ] license
- [ ] author
- [ ] support
- [ ] releases (?)

Not sure how this would be best represented visually, but I imagine the actual implementation could be 100% in the frontend/javascript.

**Comment by theimbender** [comment]
I created such a filter bar (see [my branch](https://github.com/theimbender/satis/commit/b2124960031e2c6eeff24a74e0e8d6996ec74c08)), but needed to base it off my commits from the unmerged PR #634 because I needed the updated dependencies to actually build it.

![Screen Shot 2021-02-08 at 8 46 38 PM](https://user-images.githubusercontent.com/22452104/107304320-d3e62200-6a4e-11eb-834a-9944597d0be6.png)

**Comment by alcohol** [comment]
Feel free to submit a PR for this now.
