### ISSUE TITLE
`"skip-dev": false` & `.gitattributes` file

### ISSUE THREAD

**Issue by eyalzek** [composer/satis#524]
We're running `satis` in order to mirror our php dependencies. Recently we started mirroring our private repositories as well and as a result we had to set `archive.skip-dev: false` in order to allow developers to test branches during development easily. Since there is no way to selectively set `skip-dev` per package, in effect we actually mirror all tags and branches for all packages defined in the `satis` configuration. This led to the issue described here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2098#issuecomment-461346790

Basically when specifying a combination of `skip-dev: false`,  `format: "tar"` and trying to install the package: `friendsofphp/php-cs-fixer` you can reproduce this issue yourself. As per the comments on that issue it seems like `satis`/`composer` doesn't respect the `.gitattributes` file when archiving branches. I guess this makes sense?

My question is; is there a way to "force" satis to take `.gitattributes` into consideration for dev branches? Alternatively, is there a way to set `skip-dev` only for certain requirements?

At the moment I overcome this by using `zip` packaging instead of `tar`, but this means that satis will re-download and re-package everything and will require updating many `composer.lock` files across different projects before being able to `purge`.

**Comment by SvenRtbg** [comment]
My approach to this problem (internal packages with dev, external only released tags) was to create a two-step-process: First fetch all external packages and create a minimal Satis repo without downloads, only meta data. Then another config references all local repos, and in addition as a "composer" repo the Satis repo created in step 1. This will grab all external package versions listen in there, and process them according to the local rules - which will omit any "dev" branches because the Satis repo doesn't know about them.

Possible benefit: You can run the second step more often because it will do less work with external resources.

**Comment by eyalzek** [comment]
Hmm I guess an approach with 2 separate jobs, one for public and one for private packages might work well enough. Thanks for the insight!

**Comment by eyalzek** [comment]
Seems like I was able to overcome this by setting `config.preferred-instal: dist` and `archive.rearchive: true` e.g:

```
{
    "name": "Satis",
    "config": {
      "preferred-install": "dist"
    },
    "repositories": [
        { "type": "composer", "url": "https://packagist.org" }
    ],

    "archive": {
      "directory": "dist",
      "format": "tar",
      "skip-dev": false,
      "rearchive": true
    },

    "require": {
        "friendsofphp/php-cs-fixer": "*"
    },
    "require-all": false,
    "require-dependencies": true,
    "require-dev-dependencies": true
}

I hope this doesn't have other side effects that I'm not aware of.
