### ISSUE TITLE
Having composer.json in subdirectory

### ISSUE THREAD

**Issue by zanvd-progmbh** [composer/satis#568]
Hi,

I'm currently setting up a Satis instance for our internal packages and have stumbled upon an issue with how it checks for the root of a project.

One of our libraries is going to have implementation in multiple programming languages whilst being hosted in a single repository. This means that the _composer.json_ file is not located at the root path of the repository leading to Satis failing to find it.

I've tried searching around for an option that would enable me to define the path to the composer.json file and PHP implementation's root, but there doesn't seem to be anything available.

Could someone please give me some pointers if there's a solution that I've missed?

Thank you,
Žan

**Comment by stof** [comment]
Satis relies on composer to load the metadata, so it cannot add such support.
And Composer does not support that.

**Comment by zanvd-progmbh** [comment]
So it wouldn't be possible to specify the name of the composer.json file when calling the Composer logic?
Even setting the name of composer.json would suffice as one could use _dir-name/composer.json_.

**Comment by stof** [comment]
The issue is that Composer loads remote metadata (using the github/gitlab/bitbucket API, or cloning the git/svn/... repo) so supporting multiple location in composer makes things a lot more complex.

Also, the installer would still clone your full repo (git does not allow cloning a subfolder only), making things more complex there too (as the composer.json would not be at the root of the installation folder anymore, and the whole ecosystem of plugins has this assumption currently)

**Comment by stof** [comment]
what several projects are doing is to create a (read-only) subtree split of the repository containing only the expected composer package, and point composer to that subtree repository rather than the monorepo.

If you want to go in that directly, I suggest you to use https://github.com/splitsh/lite/ to perform the split rather than `git subtree split`, for performance reasons.

**Comment by stof** [comment]
see https://github.com/laravel/framework/blob/6.x/bin/split.sh for an example of usage of this tool btw.

**Comment by zanvd-progmbh** [comment]
Thank you for an explanation and additional suggestions.

It does seem like it would introduce additional complexity, however it is a bit limiting, in my opinion, that Composer treats the repository as if it's always a package.

We are most likely going to reconsider the idea of having multiple languages of the same library in a common repository and instead have them in separate ones.
