### ISSUE TITLE
"Composer could not find a composer.json file"

### ISSUE THREAD

**Issue by MaximilianKresse** [composer/satis#707]
**Describe the bug**
When using satis in cli mode it currently throws an error:

```
Composer could not find a composer.json file in /var/www/webs/test
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
```

The given directory is the current working directory.

**To Reproduce**
```
mkdir test && cd test
php8.0 /path/to/satis/bin/satis init
php8.0 /path/to/satis/bin/satis build satis.json ./build
```

The problem is solved if I just create an empty composer.json like this:
```
{
    "name": "satis/test",
    "type": "library",
    "require": {}
}

```

**Expected behavior**
Previously no composer.json was required. Is this an intended change?

**Comment by jeanfrauc** [comment]
@MaximilianKresse Check the message "_The Satis standalone CLI requires composer. If satis is not your root project, run composer require --dev composer/composer in your root project_" they added in the `bin/satis` file when they changed the project satis to `composer-plugin` in their composer.json.
https://github.com/composer/satis/pull/701/files
Adding the command `composer require --dev composer/composer` to my CICD project worked for me without having to add a composer.json file myself.

**Comment by MaximilianKresse** [comment]
@jeanfrauc I'm a little bit confused about your answer - where do you get this error? This message doesn't pop up for me. I have simply cloned this project and used "composer update". In the default "require" is already ["composer/composer": "^2.3.10"](https://github.com/composer/satis/blob/main/composer.json#L46) so I don't see any sense to adding composer as an additional dev requirement.

I don't have a "CICD project". I had simply called "php8.0 /path/to/satis/bin/satis build satis.json /var/www/web/satis" to build my satis packages. Now I had to create a composer.json next to the satis.json.

**Comment by ralflang** [comment]
Yes, I have an idea where this comes from. A patch will be provided. As a workaround until tomorrow you may want to roll back your satis version to before that commit.

**Comment by jeanfrauc** [comment]
OK, sorry @MaximilianKresse if it wasn't clear enough.

In fact, I had exactly the same error message as you ("Composer could not find a composer.json file...") when I was building my packages.
But I am not cloning the satis project tu build my packages as you do. I am using their Docker image (which is called "composer/satis").
My CICD project is simply a Jenkinsfile in which I pull the Docker image and then I do a "docker run" with several parameters to call the satis build command.

As I didn't undertand why I was suddenly having the new error message about the composer.json, I went to see the latest merge requests created in the satis github project.
And that's where I saw that they made changes in their composer.json (the type of "composer/satis" was changed from "project" to "composer-plugin") and that they also changed the "bin/satis" file to add this code :

```
if (!class_exists('Composer\Console\Application')) {
    print("The Satis standalone CLI requires composer. If satis is not your root project, run\n
    composer require --dev composer/composer\n\nin your root project or use the equivalent plugin commands:\n
    composer satis:init
    composer satis:build
    composer satis:add
    composer satis:purge
    \n");
    exit(2);
}
```

I guess that for now satis is not working anymore like it used to but as a composer plugin.

That's why I did as they said and add a command `composer require --dev composer/composer` in my Jenkinsfile to create a composer.json before calling the satis build command (using the "composer/satis" Docker image).

**Comment by ralflang** [comment]
It should work both as a plugin (which it does) and as a standalone CLI. 

Which it did in some very limited tests after the latest commit in that PR - but obviously not in your use case.
I have already tracked down where that composer.json need crept in. A new PR will come.
I am very sorry for the inconvenience - even given we are running off an untagged development version right now.

**Comment by jeanfrauc** [comment]
Thanks @ralflang for your answer, I was indeed hoping that it should work for the both modes.
I'm waiting for the new Docker image to do some testing but in the meantime, using the `composer require` command as a workaround is working fine.

**Comment by alcohol** [comment]
Please let us know if the latest release (with #709) resolved this.

**Comment by MaximilianKresse** [comment]
It look like it's fixed now! Thank you for this fast fix!

**Comment by jeanfrauc** [comment]
The new docker image seems to work fine too. Thanks
