### ISSUE TITLE
403 when trying to access packages.json

### ISSUE THREAD

**Issue by Eddcapone** [composer/satis#720]
**Describe the bug**
Can't access packages.json. I get 403

**To Reproduce**
After generating my files with ` php bin/satis build satis.json pub` there is a package.json in `pub`.
My domain is pointing to that pub directory. But if I try to load packages.json with www.example.org/packages.json then I get 403 Forbidden.

**Comment by alcohol** [comment]
Server configuration, sorry. Not a Satis related issue.

**Comment by Eddcapone** [comment]
No, if I just create a new file in that directory e.g. test.json, then I can call it.

**Comment by SvenRtbg** [comment]
Still it's the responsibility of your server to serve the files created by Satis. Compare user and group assignment and access rights of the file created manually and by Satis. Any observations? It might be your web server is rejecting access either because of a mismatch of the user or group, or because of missing _or excessive_ access rights. Also consider the entire path from the root directory up to your target file location.

**Comment by SvenRtbg** [comment]
Perfectly valid decision on their side, as it sounds like something non-technical people may be doing wrong when publishing something on the internet, i.e. accidentially pushing a "packages.json" from their Javascript website revealing all the vulnerable dependencies they are using.

**Comment by Eddcapone** [comment]
Yes they have disabled access to that file. But they are using ModSecurity and I was able to disable it for the satis domain.
