### ISSUE TITLE
`includes` configuration is documented but not valid

### ISSUE THREAD

**Issue by drumm** [composer/satis#751]
**Describe the bug**
https://github.com/composer/satis/blob/main/docs/config.md#includes says `includes` can be configured.

https://github.com/composer/satis/blob/main/res/satis-schema.json does not have it.

**To Reproduce**
```
{
    "name": "drupal/test",
    "homepage": "http://test.example.org",
    "repositories": [
        { "type": "vcs", "url": "https://github.com/drupal/core-composer-scaffold.git" },
        { "type": "vcs", "url": "https://github.com/drupal/core-project-message.git" },
        { "type": "vcs", "url": "https://github.com/drupal/core.git" },
        { "type": "vcs", "url": "https://github.com/drupal/core-recommended.git" }
    ],
    "require-all": true,
    "includes": true,
    "archive": {
        "directory": "dist",
        "prefix-url": "http://test.example.org"
    }
}
```

`satis build --minify satis.json output`

**Outcome**

Attempting to use it errors with

```
The property includes is not defined and the definition does not allow additional properties

In BuildCommand.php line 348:

  The json config file does not match the expected JSON schema
```

**Expected behavior**

I do not want to support Composer 1.

**Comment by alcohol** [comment]
Looks like https://github.com/composer/satis/commit/73922c744dd68224a33375576f17dbef269c553b was incomplete. Odd that this was not reported earlier though. I guess because it defaults to `true` in the code, the only use case is when you explicitly do not want it (setting it to `false`) or when you want your configuration to be explicit rather than default.
